# -*- coding: utf-8 -*-
"""PDF417_barkod_yap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ncr7bIiwpGtge0CDXYSF-GDANAVh2FB9
"""

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)
from google.colab import drive
drive.mount('/content/drive')

!pip install aztec-code-generator
!pip3 install https://github.com/dlenski/aztec_code_generator/archive/master.zip
!pip install pyStrich
!!pip install opencv-python
!pip install barcode-image-composer
!pip install python-barcode pylibdmtx opencv-python pillow
!apt-get -qq install -y barcode-image-composer && pip install -U barcode-image-composer
!pip install argparse
!pip install imgcomposer
!pip3 install pylibdmtx
!sudo apt-get install libdmtx0a
!pip install pylibdmtx
!pip install pylibdmtx[scripts]
!pip install pdf417

import glob
import cv2
import pandas as pd
import pathlib

from PIL import Image
from pdf417 import encode, render_image, render_svg

import pandas as pd
import numpy as np

import csv
rows = []
mesut=1;
with open("/content/drive/MyDrive/pdf malware/dataset2/no.csv", 'r') as file:
    csvreader = csv.reader(file)
    for row in csvreader:
        rows.append(row)
        row1=str(row)
        #print(row)
        codes = encode(row1, columns=10, security_level=8)
        # Generate barcode as image
        image = render_image(codes)  # Pillow Image object
        image.save(f"/content/drive/MyDrive/pdf malware/dataset2/no/no{mesut}.png")
        mesut=mesut+1
        if mesut % 1000 == 0:
          print(mesut)
print(mesut)